name: Bug report
description: Report a reproducible problem
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true
  - type: input
    attributes:
      label: Package version
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: Link to a minimal repository or include minimal code.
    validations:
      required: true
